### PR TITLE
Article as arranged with Matt Venn, ready for publishing

### PR DESCRIPTION
**Pull request by suarezvictor**

### CODE REVIEW

**Comment by JulianKemmerer** [comment]
:raised_hands:

**Comment by mattvenn** [comment]
published. I'll do the social media / linked in business soon

**Comment by mattvenn** [comment]
thanks!

**Comment by JulianKemmerer** [comment]
@mattvenn do you mind giving a shout when social media stuff is up? maybe share some links? I would love to help spread the word :raised_hands:  :)

**Comment by mattvenn** [comment]
https://twitter.com/YosysHQ/status/1622556115689938944
https://fosstodon.org/@yosyshq/109817541635317677
https://www.linkedin.com/posts/yosyshq_opensource-fpga-activity-7028323859992842241-qlpp

**Pull request merged**
